export const places = {
  source: 'places',
  list : [
    { title: 'Казино', img: 'casino'},
    { title: 'Кладбище', img: 'graveyard'},
    { title: 'Круизный лайнер', img: 'сruise_ship'},
    { title: 'Самолёт', img: 'plane'},
    { title: 'Отель', img: 'hotel'},
    { title: 'Закусочная', img: 'eatery'},
    { title: 'Ресторан', img: 'restaurant'},
    { title: 'Транажёрный Зал', img: 'gym'},
    { title: 'Космическая Станция', img: 'space_station'},
    { title: 'Стадион', img: 'stadium'},
    { title: 'Стройплощадка', img: 'construction_site'},
    { title: 'Тюрьма', img: 'jail'},
    { title: 'Выставка кошек', img: 'cat_show'},
    { title: 'Пиратский корабль', img: 'pirate_ship'},
    { title: 'Торговый центр', img: 'shopping_centre'},
    { title: 'Бассейн', img: 'pool'},
    { title: 'Кинотеатр', img: 'cinema'},
    { title: 'Киностудия', img: 'film_studio'},
    { title: 'Церковь', img: 'church'},
    { title: 'Ночной Клуб', img: 'night_club'},
    { title: 'Спа-салон', img: 'spa'},
    { title: 'Школа', img: 'school'},
    { title: 'Полицейский участок', img: 'police_station'},
    { title: 'Подводная лодка', img: 'submarine'},
    { title: 'Цирк', img: 'circus'},
    { title: 'Парк Развлечений', img: 'entertainment_park'},
    { title: 'Посольство', img: 'embassy'},
    { title: 'Карнавал', img: 'carnival'},
    { title: 'Пляж', img: 'beach'},
    { title: 'Воинская часть', img: 'military_unit'},
    { title: 'Университет', img: 'university'},
    { title: 'Больница', img: 'hospital'},
    { title: 'Театр', img: 'theatre'},
    { title: 'Зоопарк', img: 'zoo'},
    { title: 'Пассажирский Поезд', img: 'passenger_train'},
    { title: 'Вечеринка', img: 'party'},
    { title: 'Шахта', img: 'mine'},
    { title: 'Рок-концерт', img: 'rock_concert'},
    { title: 'Библиотека', img: 'library'},
    { title: 'Свадьба', img: 'wedding'},
  ],
}